stages:
    - build
    - deploy dev
    - test dev
    - deploy prod
    - test prod

build:
    stage: build
    script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    # only:
    #     changes:
    #         - Dockerfile
    #         - server.go

deploy dev:
    stage: deploy dev
    variables:
        DOCKER_HOST: tcp://web1.sikademo.com:2376
    script:
        - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
        - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
        - docker rm -f $CI_COMMIT_REF_SLUG || true
        - docker run -d --network traefik --name $CI_COMMIT_REF_SLUG -l traefik.enable=true -l traefik.frontend.rule=Host:$CI_COMMIT_REF_SLUG.web1.sikademo.com $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    environment:
        name: dev/$CI_COMMIT_REF_SLUG
        url: https://$CI_COMMIT_REF_SLUG.web1.sikademo.com

test dev:
    stage: test dev
    script:
        - curl -k https://$CI_COMMIT_REF_SLUG.web1.sikademo.com
